//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.BL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_BL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_BL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.BL.Properties.Strings_BL", typeof(Strings_BL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldName property is missing from MetaData being validated..
        /// </summary>
        internal static string MetaData_Error_MissingFieldName {
            get {
                return ResourceManager.GetString("MetaData_Error_MissingFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldValue property is missing from MetaData being validated..
        /// </summary>
        internal static string MetaData_Error_MissingFieldValue {
            get {
                return ResourceManager.GetString("MetaData_Error_MissingFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableName property is missing from MetaData being validated..
        /// </summary>
        internal static string MetaData_Error_MissingTableName {
            get {
                return ResourceManager.GetString("MetaData_Error_MissingTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldName property is missing from MetaDataRule being validated..
        /// </summary>
        internal static string MetaDataRule_Error_MissingFieldName {
            get {
                return ResourceManager.GetString("MetaDataRule_Error_MissingFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value is required for Meta Data Rule..
        /// </summary>
        internal static string MetaDataRule_Error_MissingNewValue {
            get {
                return ResourceManager.GetString("MetaDataRule_Error_MissingNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldValue property is missing from MetaDataRule being validated..
        /// </summary>
        internal static string MetaDataRule_Error_MissingOldValue {
            get {
                return ResourceManager.GetString("MetaDataRule_Error_MissingOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableName property is missing from MetaDataRule being validated..
        /// </summary>
        internal static string MetaDataRule_Error_MissingTableName {
            get {
                return ResourceManager.GetString("MetaDataRule_Error_MissingTableName", resourceCulture);
            }
        }
    }
}
