//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.wpf.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Metadata Rules.
        /// </summary>
        internal static string AllMetaDataRulesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllMetaDataRulesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete an invalid MetaData Rule..
        /// </summary>
        internal static string AllMetaDataRulesViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("AllMetaDataRulesViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPSI Next Gen -- Admininstration Utilities.
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all source data table names..
        /// </summary>
        internal static string MainWindowViewModel_GetTableNames {
            get {
                return ResourceManager.GetString("MainWindowViewModel_GetTableNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid MetaData Rule..
        /// </summary>
        internal static string MetaDataRuleViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("MetaDataRuleViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Rule Maker.
        /// </summary>
        internal static string MetaMakerViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MetaMakerViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid MetaData Rule..
        /// </summary>
        internal static string MetaMakerViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("MetaMakerViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Meta Source Data.
        /// </summary>
        internal static string MetaMakerViewModel_GetMetaSourceData {
            get {
                return ResourceManager.GetString("MetaMakerViewModel_GetMetaSourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Meta Source Fields.
        /// </summary>
        internal static string MetaMakerViewModel_GetMetaSourceFields {
            get {
                return ResourceManager.GetString("MetaMakerViewModel_GetMetaSourceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Data.
        /// </summary>
        internal static string StageDataViewModel_DisplayName {
            get {
                return ResourceManager.GetString("StageDataViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
